<?php

namespace Database\Seeders;

use App\Models\Organization;
use Illuminate\Database\Seeder;

class OrganizationSeeder extends Seeder
{
    /**
     * Seed the default organizations. Safe to re-run.
     */
    public function run(): void
    {
        $organizations = [
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL ACAPULCO',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL ALTAMIRA',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL COATZACOALCOS',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL DOS BOCAS',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL ENSENADA',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL GUAYMAS',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL LÁZARO CÁRDENAS',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL MANZANILLO',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL MAZATLÁN',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL PROGRESO',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL PUERTO VALLARTA',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL SALINA CRUZ',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL TAMPICO',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL TOPOLOBAMPO',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL TUXPAN',
            'ADMINISTRACIÓN DEL SISTEMA PORTUARIO NACIONAL VERACRUZ',
            'AEROPUERTO INTERNACIONAL DE LA CIUDAD DE MÉXICO',
            'AEROPUERTO INTERNACIONAL FELIPE ÁNGELES',
            'AEROPUERTOS Y SERVICIOS AUXILIARES',
            'BANCO NACIONAL DE COMERCIO EXTERIOR',
            'BANCO NACIONAL DE OBRAS Y SERVICIOS PÚBLICOS',
            'BANCO NACIONAL DEL EJÉRCITO',
            'CAMINOS Y PUENTES FEDERALES DE INGRESOS Y SERVICIOS CONEXOS',
            'CASA DE MONEDA DE MÉXICO',
            'CENTRO DE INNOVACIÓN APLICADA EN TECNOLOGÍAS COMPETITIVAS',
            'CENTRO NACIONAL DE CONTROL DEL GAS NATURAL',
            'COMISIÓN EJECUTIVA DE ATENCIÓN A VÍCTIMAS',
            'COMISIÓN NACIONAL DE ACUACULTURA Y PESCA',
            'COMISIÓN NACIONAL DE ÁREAS NATURALES PROTEGIDAS',
            'COMISIÓN NACIONAL DE CULTURA FÍSICA Y DEPORTE',
            'COMISIÓN NACIONAL DE LIBROS DE TEXTO GRATUITOS',
            'COMISIÓN NACIONAL DEL AGUA',
            'COMISIÓN NACIONAL DEL SISTEMA DE AHORRO PARA EL RETIRO',
            'COMISIÓN NACIONAL FORESTAL',
            'COMISIÓN NACIONAL PARA EL USO EFICIENTE DE LA ENERGÍA',
            'COMISIÓN NACIONAL PARA LA PROTECCIÓN Y DEFENSA DE LOS USUARIOS DE SERVICIOS FINANCIEROS',
            'COMPAÑÍA OPERADORA DEL CENTRO CULTURAL Y TURÍSTICO DE TIJUANA',
            'CONSEJO NACIONAL PARA PREVENIR LA DISCRIMINACIÓN',
            'FIDEICOMISO DE FOMENTO MINERO',
            'FINANCIERA PARA EL BIENESTAR',
            'FONDO DE CULTURA ECONÓMICA',
            'FONDO NACIONAL DE FOMENTO AL TURISMO',
            'FONDO NACIONAL PARA EL FOMENTO DE LAS ARTESANÍAS',
            'GRUPO AEROPORTUARIO',
            'INSTITUTO DE SEGURIDAD SOCIAL PARA LAS FUERZAS ARMADAS MEXICANAS',
            'INSTITUTO DE SEGURIDAD Y SERVICIOS SOCIALES DE LOS TRABAJADORES DEL ESTADO',
            'INSTITUTO DEL FONDO NACIONAL PARA EL CONSUMO DE LOS TRABAJADORES',
            'INSTITUTO MEXICANO DE CINEMATOGRAFÍA',
            'INSTITUTO MEXICANO DE LA JUVENTUD',
            'INSTITUTO MEXICANO DE LA PROPIEDAD INDUSTRIAL',
            'INSTITUTO MEXICANO DE LA RADIO',
            'INSTITUTO MEXICANO DEL PETRÓLEO',
            'INSTITUTO MEXICANO DEL SEGURO SOCIAL',
            'INSTITUTO NACIONAL DE ANTROPOLOGÍA E HISTORIA',
            'INSTITUTO NACIONAL DE ASTROFÍSICA',
            'INSTITUTO NACIONAL DE BELLAS ARTES Y LITERATURA',
            'INSTITUTO NACIONAL DE LAS PERSONAS ADULTAS MAYORES',
            'INSTITUTO NACIONAL DE LENGUAS INDÍGENAS',
            'INSTITUTO NACIONAL DE LOS PUEBLOS INDÍGENAS',
            'INSTITUTO NACIONAL DEL DERECHO DE AUTOR',
            'INSTITUTO NACIONAL PARA LA EDUCACIÓN DE LOS ADULTOS',
            'INSTITUTO PARA LA PROTECCIÓN AL AHORRO BANCARIO',
            'INSTITUTO POLITÉCNICO NACIONAL',
            'LOTERÍA NACIONAL',
            'NACIONAL FINANCIERA',
            'PROCURADURÍA FEDERAL DE PROTECCIÓN AL AMBIENTE',
            'PROCURADURÍA FEDERAL DEL CONSUMIDOR',
            'RADIO EDUCACIÓN',
            'SECRETARÍA ANTICORRUPCIÓN Y BUEN GOBIERNO',
            'SECRETARÍA DE AGRICULTURA Y DESARROLLO RURAL',
            'SECRETARÍA DE BIENESTAR',
            'SECRETARÍA DE CIENCIA',
            'SECRETARÍA DE CULTURA',
            'SECRETARÍA DE ECONOMÍA',
            'SECRETARÍA DE EDUCACIÓN PÚBLICA',
            'SECRETARÍA DE ENERGÍA',
            'SECRETARÍA DE GOBERNACIÓN',
            'SECRETARÍA DE HACIENDA Y CRÉDITO PÚBLICO',
            'SECRETARÍA DE INFRAESTRUCTURA',
            'SECRETARÍA DE LA DEFENSA NACIONAL',
            'SECRETARÍA DE LAS MUJERES',
            'SECRETARÍA DE MARINA',
            'SECRETARÍA DE MEDIO AMBIENTE Y RECURSOS NATURALES',
            'SECRETARÍA DE RELACIONES EXTERIORES',
            'SECRETARÍA DE SALUD',
            'SECRETARÍA DE TURISMO',
            'SECRETARÍA DEL TRABAJO Y PREVISIÓN SOCIAL',
            'SECRETARÍA GENERAL DEL CONSEJO NACIONAL DE POBLACIÓN',
            'SERVICIO GEOLÓGICO MEXICANO',
            'SERVICIO NACIONAL DE SANIDAD',
            'SERVICIOS DE SALUD DEL INSTITUTO MEXICANO DEL SEGURO SOCIAL PARA EL BIENESTAR',
            'TREN MAYA',
        ];

        foreach ($organizations as $name) {
            Organization::firstOrCreate(['name' => $name]);
        }
    }
}
